apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: sample-nodejs-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sample-nodejs-app
    app.kubernetes.io/part-of: sample-nodejs-app
  name: sample-nodejs-app
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: sample-nodejs-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: sample-nodejs-app
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rhn-support-bpimente-tenant/sample-nodejs-app/sample-nodejs-app@sha256:d60592ddd6c5036fe74a367b4c93a5f7bdc9c280d07182ea6f9ad1393338d363
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 9000
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
