apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: sample-nodejs-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sample-nodejs-app
    app.kubernetes.io/part-of: sample-nodejs-app
  name: sample-nodejs-app
spec:
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    app.kubernetes.io/instance: sample-nodejs-app
status:
  loadBalancer: {}
